name: Scheduled Build

on:
  schedule:
    - cron: "0 0 * * *"   # every day at 00:00 UTC
  workflow_dispatch:     

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log completion message
        run: echo "Scheduled build completed successfully!"
